"""
codegen.py — C Code Generator (Enhanced + Fixed)
==================================================
Translates structured IR instructions into clean, compilable C code.
"""

from ir import IRInstruction


class CodeGenerator:
    """Translates IR instructions → valid C source string."""

    def __init__(self):
        self._lines = []
        self._indent = 0
        self._func_names = set()     # known function names
        self._func_params = {}       # func_name → [param_names]
        self._param_buffer = []      # buffered PARAM instructions for next CALL

    def _emit(self, line=''):
        self._lines.append('    ' * self._indent + line)

    # ── Main entry point ──────────────────────────────────────

    def generate(self, instructions):
        # Pass 1: find function definitions
        self._scan_functions(instructions)

        # Pass 2: emit C code
        self._emit('/*')
        self._emit(' * output.c — Generated by Mini Python Compiler')
        self._emit(' * Compile:  gcc output.c -o output -lm')
        self._emit(' * Run:      ./output')
        self._emit(' */')
        self._emit('#include <stdio.h>')
        self._emit('#include <math.h>')
        self._emit()

        # Forward declarations
        for fname, params in self._func_params.items():
            param_str = ', '.join(f'double {p}' for p in params)
            self._emit(f'double {fname}({param_str});')
        if self._func_params:
            self._emit()

        # Separate function defs from main-body instructions
        main_instrs = []
        i = 0
        while i < len(instructions):
            instr = instructions[i]
            if instr.op == 'func_begin':
                func_end = self._find_func_end(instructions, i)
                self._emit_function(instructions[i:func_end + 1])
                self._emit()
                i = func_end + 1
            else:
                main_instrs.append(instr)
                i += 1

        # Emit main()
        self._emit('int main() {')
        self._indent = 1

        main_vars = self._collect_vars(main_instrs)
        if main_vars:
            for v in sorted(main_vars):
                self._emit(f'double {v} = 0;')
            self._emit()

        for instr in main_instrs:
            self._emit_instr(instr)

        self._emit()
        self._emit('return 0;')
        self._indent = 0
        self._emit('}')

        return '\n'.join(self._lines)

    # ── Function emission ─────────────────────────────────────

    def _emit_function(self, instrs):
        header = instrs[0]
        fname = header.arg1
        params = header.extra or []
        param_str = ', '.join(f'double {p}' for p in params)

        self._emit(f'double {fname}({param_str}) {{')
        self._indent = 1

        body = instrs[1:-1]
        local_vars = self._collect_vars(body) - set(params)
        for v in sorted(local_vars):
            self._emit(f'double {v} = 0;')
        if local_vars:
            self._emit()

        for instr in body:
            self._emit_instr(instr)

        self._indent = 0
        self._emit('}')

    # ── Instruction emission ──────────────────────────────────

    def _emit_instr(self, instr):
        op = instr.op

        if op == 'assign':
            self._emit(f'{instr.result} = {self._val(instr.arg1)};')

        elif op == 'binop':
            self._emit(f'{instr.result} = {self._val(instr.arg1)} {instr.operator} {self._val(instr.arg2)};')

        elif op == 'compare':
            self._emit(f'{instr.result} = {self._val(instr.arg1)} {instr.operator} {self._val(instr.arg2)};')

        elif op == 'unary':
            self._emit(f'{instr.result} = {instr.operator}{self._val(instr.arg1)};')

        elif op == 'print':
            self._emit(f'printf("%g\\n", {self._val(instr.arg1)});')

        elif op == 'print_str':
            self._emit(f'printf("%s\\n", "{instr.arg1}");')

        elif op == 'if_begin':
            self._emit(f'if ({instr.arg1}) {{')
            self._indent += 1

        elif op == 'else':
            self._indent -= 1
            self._emit('} else {')
            self._indent += 1

        elif op == 'if_end':
            self._indent -= 1
            self._emit('}')

        elif op == 'while_begin':
            self._emit('while (1) {')
            self._indent += 1

        elif op == 'while_cond':
            self._emit(f'if (!({instr.arg1})) break;')

        elif op == 'while_end':
            self._indent -= 1
            self._emit('}')

        elif op == 'return':
            self._emit(f'return {self._val(instr.arg1)};')

        elif op == 'param':
            self._param_buffer.append(instr.arg1)

        elif op == 'call':
            args = list(self._param_buffer)
            self._param_buffer.clear()
            arg_str = ', '.join(self._val(a) for a in args)
            self._emit(f'{instr.result} = {instr.arg1}({arg_str});')

    # ── Helpers ───────────────────────────────────────────────

    def _val(self, v):
        """Format a value for C output — all numbers become double literals
        so they work correctly with printf("%g", ...) and double variables."""
        if v is None:
            return '0.0'
        if self._is_literal(v):
            f = float(v)
            # Always output as a double literal: 1 → 1.0,  3.14 → 3.14
            if '.' not in str(v) and 'e' not in str(v).lower():
                return f'{f:.1f}'   # 1 → "1.0",  42 → "42.0"
            return str(f)
        return v

    def _scan_functions(self, instructions):
        """Pre-scan to find all function names and their params."""
        for instr in instructions:
            if instr.op == 'func_begin':
                self._func_names.add(instr.arg1)
                self._func_params[instr.arg1] = instr.extra or []

    def _collect_vars(self, instrs):
        """Collect variable names from instructions, excluding literals,
        function names, string values, and structural markers."""
        names = set()
        for instr in instrs:
            # Only collect from result/arg1/arg2 for data instructions
            if instr.op in ('assign', 'binop', 'compare', 'unary'):
                if instr.result and self._is_var(instr.result):
                    names.add(instr.result)
                if instr.arg1 and self._is_var(instr.arg1):
                    names.add(instr.arg1)
                if instr.arg2 and self._is_var(instr.arg2):
                    names.add(instr.arg2)
            elif instr.op == 'print':
                if instr.arg1 and self._is_var(instr.arg1):
                    names.add(instr.arg1)
            elif instr.op == 'call':
                if instr.result and self._is_var(instr.result):
                    names.add(instr.result)
                # arg1 is func name — skip it
                # arg2 is count — skip it
            elif instr.op == 'param':
                if instr.arg1 and self._is_var(instr.arg1):
                    names.add(instr.arg1)
            elif instr.op in ('if_begin', 'while_cond'):
                if instr.arg1 and self._is_var(instr.arg1):
                    names.add(instr.arg1)
            elif instr.op == 'return':
                if instr.arg1 and self._is_var(instr.arg1):
                    names.add(instr.arg1)
        return names

    def _is_var(self, value):
        """True if value is a variable name (not a literal, not a function name)."""
        if not isinstance(value, str):
            return False
        if self._is_literal(value):
            return False
        if value in self._func_names:
            return False
        return True

    def _find_func_end(self, instrs, start):
        depth = 0
        for i in range(start, len(instrs)):
            if instrs[i].op == 'func_begin':
                depth += 1
            elif instrs[i].op == 'func_end':
                depth -= 1
                if depth == 0:
                    return i
        return len(instrs) - 1

    @staticmethod
    def _is_literal(value):
        try:
            float(value)
            return True
        except (ValueError, TypeError):
            return False
