/* Generated by the Python-subset compiler */
#include <math.h>
#include "py_runtime.h"

const char * greet(const char * name);

const char * greet(const char * name) {
    const char * _t4 = "";
    const char * _t5 = "";

entry_2: ;
    py_decref(_t4);
    _t4 = "Hello ";
    py_incref(_t4);
    py_decref(_t5);
    _t5 = py_str_concat(_t4, name);
    py_incref(_t5);
    py_decref(_t4);
    py_decref(_t5);
    return _t5;
}

int main(void) {
    const char * _t1 = "";
    const char * _t2 = "";
    const char * _t3 = "";

entry_1: ;
    py_decref(_t1);
    _t1 = "World";
    py_incref(_t1);
    py_decref(_t2);
    _t2 = greet(_t1);
    py_write_str(_t2);
    py_decref(_t3);
    _t3 = "\n";
    py_incref(_t3);
    py_write_str(_t3);
    py_decref(_t1);
    py_decref(_t2);
    py_decref(_t3);
    return 0;
}
