/*
 * output.c — Generated by Mini Python Compiler
 * Compile:  gcc output.c -o output -lm
 * Run:      ./output
 */
#include <stdio.h>
#include <math.h>

int main() {
    double a = 0;
    double b = 0;
    double c = 0;
    double t1 = 0;
    double t2 = 0;
    double t3 = 0;
    double x = 0;
    
    a = 0.0;
    b = 1.0;
    printf("%g\n", a);
    printf("%g\n", b);
    printf("%g\n", 0.0);
    printf("%g\n", 0.0);
    c = -10.0;
    printf("%g\n", c);
    x = 1.0;
    t1 = x + 1.0;
    x = t1;
    t2 = x + 1.0;
    x = t2;
    t3 = x + 1.0;
    x = t3;
    printf("%g\n", x);
    
    return 0;
}
