/* Generated by the Python-subset compiler */
#include <math.h>
#include "py_runtime.h"

int main(void) {
    py_clear_error();
    int __ret_value = 0;
    const char * _t1 = NULL;
    const char * _t2 = NULL;
    double _t3 = 0;
    const char * _t4 = NULL;
    const char * _t5 = NULL;
    int _t6 = 0;

entry_1: ;
    py_decref(_t1);
    _t1 = "Exception";
    py_incref(_t1);
    py_decref(_t2);
    _t2 = "boom";
    py_incref(_t2);
    _t3 = Exception(_t2);
    if (py_error_occurred()) goto except_2;
    py_set_error(_t1, _t3);
    goto except_2;
except_2: ;
    goto try_finally_4;
try_merge_3: ;
    __ret_value = 0;
    goto cleanup;
try_finally_4: ;
    py_decref(_t4);
    _t4 = "done";
    py_incref(_t4);
    py_write_str(_t4);
    py_decref(_t5);
    _t5 = "\n";
    py_incref(_t5);
    py_write_str(_t5);
    _t6 = py_error_occurred();
    if (py_truthy_int(_t6)) goto try_finally_error_5;
    goto try_merge_3;
try_finally_error_5: ;
    goto cleanup;
cleanup: ;
    if (_t5) py_decref(_t5);
    if (_t4) py_decref(_t4);
    if (_t2) py_decref(_t2);
    if (_t1) py_decref(_t1);
    if (py_error_occurred()) {
        return 0;
    }
    return __ret_value;
}
