/* Generated by the Python-subset compiler */
#include "py_runtime.h"

int square(int x);
int add(int x, int y);

int square(int x) {
    int _t35 = 0;

entry_7: ;
    _t35 = x * x;
    return _t35;
}

int add(int x, int y) {
    int _t36 = 0;

entry_8: ;
    _t36 = x + y;
    return _t36;
}

int main(void) {
    int _t1 = 0;
    const char * _t10 = "";
    int _t11 = 0;
    const char * _t12 = "";
    int _t13 = 0;
    const char * _t14 = "";
    int _t15 = 0;
    int _t16 = 0;
    const char * _t17 = "";
    int _t18 = 0;
    int _t19 = 0;
    int _t2 = 0;
    int _t20 = 0;
    const char * _t21 = "";
    int _t22 = 0;
    int _t23 = 0;
    const char * _t24 = "";
    int _t25 = 0;
    int _t26 = 0;
    int _t27 = 0;
    const char * _t28 = "";
    int _t29 = 0;
    int _t3 = 0;
    int _t30 = 0;
    int _t31 = 0;
    const char * _t32 = "";
    const char * _t33 = "";
    const char * _t34 = "";
    const char * _t4 = "";
    int _t5 = 0;
    const char * _t6 = "";
    int _t7 = 0;
    const char * _t8 = "";
    double _t9 = 0.0;
    int a = 0;
    int b = 0;
    int folded = 0;
    int folded__ssa_1 = 0;
    int i = 0;
    int i__ssa_1 = 0;
    int i__ssa_2 = 0;

entry_1: ;
    _t3 = 14;
    py_write_int(_t3);
    _t4 = "\n";
    py_write_str(_t4);
    _t5 = 6;
    py_write_int(_t5);
    _t6 = "\n";
    py_write_str(_t6);
    _t7 = 40;
    py_write_int(_t7);
    _t8 = "\n";
    py_write_str(_t8);
    _t9 = 2.5;
    py_write_float(_t9);
    _t10 = "\n";
    py_write_str(_t10);
    _t11 = 14;
    py_write_int(_t11);
    _t12 = "\n";
    py_write_str(_t12);
    _t13 = 20;
    py_write_int(_t13);
    _t14 = "\n";
    py_write_str(_t14);
    _t15 = 5;
    _t16 = square(_t15);
    py_write_int(_t16);
    _t17 = "\n";
    py_write_str(_t17);
    _t18 = 10;
    _t19 = 20;
    _t20 = add(_t18, _t19);
    py_write_int(_t20);
    _t21 = "\n";
    py_write_str(_t21);
    goto then_2;
then_2: ;
    _t23 = 42;
    py_write_int(_t23);
    _t24 = "\n";
    py_write_str(_t24);
    goto merge_3;
merge_3: ;
    i__ssa_1 = 3;
    goto ssa_edge_1;
while_cond_4: ;
    _t26 = 0;
    _t27 = i__ssa_2 > _t26;
    if (_t27) goto while_body_5;
    goto while_exit_6;
while_body_5: ;
    py_write_int(i__ssa_2);
    _t28 = "\n";
    py_write_str(_t28);
    _t29 = 1;
    _t30 = i__ssa_2 - _t29;
    goto ssa_edge_2;
while_exit_6: ;
    folded__ssa_1 = 600;
    py_write_int(folded__ssa_1);
    _t32 = "\n";
    py_write_str(_t32);
    _t33 = "All tests passed!";
    py_write_str(_t33);
    _t34 = "\n";
    py_write_str(_t34);
    return 0;
ssa_edge_1: ;
    i__ssa_2 = i__ssa_1;
    goto while_cond_4;
ssa_edge_2: ;
    i__ssa_2 = _t30;
    goto while_cond_4;
}
