from __future__ import annotations

from compiler.core.types import ValueType, c_type_name
from compiler.ir import (
    Assign,
    BasicBlock,
    BinaryOp,
    BranchTerminator,
    Call,
    DecRef,
    IRFunction,
    IRModule,
    JumpTerminator,
    LoadConst,
    Print,
    ReturnTerminator,
    UnaryOp,
)
from compiler.runtime import CRuntimeSupport


class CCodeGenerator:
    def __init__(self) -> None:
        self.runtime = CRuntimeSupport()
        self._temp_id = 0

    def generate(self, module: IRModule) -> str:
        lines = [
            "/* Generated by the Python-subset compiler */",
            "#include <math.h>",
            self.runtime.include_directive(),
            "",
        ]

        for name, value_type in sorted(module.globals.items()):
            lines.append(
                f"{c_type_name(value_type)} {name} = {self._default_initializer(value_type)};"
            )

        if module.globals:
            lines.append("")

        for function in module.functions:
            lines.append(self._prototype(function) + ";")

        if module.functions:
            lines.append("")

        for function in module.functions:
            lines.extend(self._emit_function(function))
            lines.append("")

        lines.extend(self._emit_main(module.main))

        return "\n".join(lines).rstrip() + "\n"

    def _emit_main(self, function: IRFunction) -> list[str]:
        lines = ["int main(void) {"]
        lines.append("    py_clear_error();")
        lines.append("    py_runtime_init();")

        if function.return_type != ValueType.VOID:
            lines.append(
                f"    {c_type_name(function.return_type)} __ret_value = {self._default_initializer(function.return_type)};"
            )
        lines.extend(self._emit_locals(function))
        lines.extend(self._emit_blocks(function.blocks, function, "__ret_value"))
        lines.extend(self._emit_cleanup(function, "__ret_value"))
        lines.append("}")
        return lines

    def _emit_function(self, function: IRFunction) -> list[str]:
        lines = [f"{self._prototype(function)} {{"]
        lines.append("    py_clear_error();")

        if function.return_type != ValueType.VOID:
            lines.append(
                f"    {c_type_name(function.return_type)} __ret_value = {self._default_initializer(function.return_type)};"
            )

        lines.extend(self._emit_locals(function))
        lines.extend(self._emit_blocks(function.blocks, function, "__ret_value"))
        lines.extend(self._emit_cleanup(function, "__ret_value"))

        lines.append("}")
        return lines

    def _prototype(self, function: IRFunction) -> str:
        params = ", ".join(
            f"{c_type_name(value_type)} {name}"
            for name, value_type in function.params
        )

        return f"{c_type_name(function.return_type)} {function.name}({params or 'void'})"

    def _emit_locals(self, function: IRFunction) -> list[str]:
        locals_only = {
            name: value_type
            for name, value_type in function.locals.items()
            if name not in dict(function.params)
        }

        if not locals_only:
            return []

        lines = []

        for name, value_type in sorted(locals_only.items()):
            lines.append(
                f"    {c_type_name(value_type)} {name} = {self._default_initializer(value_type)};"
            )

        lines.append("")
        return lines

    def _emit_blocks(
        self,
        blocks: list[BasicBlock],
        function: IRFunction,
        ret_var: str,
    ) -> list[str]:

        type_map = self._build_type_map(function)

        lines: list[str] = []

        for block in blocks:
            lines.append(f"{block.name}: ;")

            for instruction in block.instructions:

                if isinstance(instruction, LoadConst):
                    if self.runtime.is_refcounted(instruction.value_type):
                        lines.append(
                            f"    py_decref({instruction.target});"
                        )
                    lines.append(
                        f"    {instruction.target} = "
                        f"{self._literal(instruction.value, instruction.value_type)};"
                    )
                    if self.runtime.is_refcounted(instruction.value_type):
                        lines.append(
                            f"    py_incref({instruction.target});"
                        )

                elif isinstance(instruction, Assign):
                    target_type = type_map.get(instruction.target, ValueType.UNKNOWN)
                    if self.runtime.is_refcounted(target_type):
                        lines.append(
                            f"    py_decref({instruction.target});"
                        )
                    lines.append(
                        f"    {instruction.target} = {instruction.source};"
                    )
                    if self.runtime.is_refcounted(target_type):
                        lines.append(
                            f"    py_incref({instruction.target});"
                        )

                elif isinstance(instruction, BinaryOp):

                    # string concatenation
                    if (
                        instruction.value_type == ValueType.STRING
                        and instruction.op == "+"
                    ):
                        if type_map.get(instruction.target) == ValueType.STRING:
                            lines.append(
                                f"    py_decref({instruction.target});"
                            )
                        lines.append(
                            f"    {instruction.target} = "
                            f"py_str_concat({instruction.left}, {instruction.right});"
                        )
                        lines.append(
                            "    if (py_error_occurred()) goto cleanup;"
                        )

                    else:
                        left = instruction.left
                        right = instruction.right
                        op = instruction.op

                        # float promotion
                        if (
                            instruction.value_type == ValueType.FLOAT
                            and op in {"+", "-", "*", "/", "%"}
                        ):
                            left = f"((double) {left})"
                            right = f"((double) {right})"

                        # Python floor division
                        if op == "//":
                            if instruction.value_type == ValueType.FLOAT:
                                lines.append(
                                    f"    {instruction.target} = floor({left} / {right});"
                                )
                            else:
                                lines.append(
                                    f"    {instruction.target} = py_floor_div_int({left}, {right});"
                                )
                                lines.append(
                                    "    if (py_error_occurred()) goto cleanup;"
                                )

                        # Python exponentiation
                        elif op == "**":
                            if instruction.value_type == ValueType.FLOAT:
                                lines.append(
                                    f"    {instruction.target} = pow({left}, {right});"
                                )
                            else:
                                lines.append(
                                    f"    {instruction.target} = py_pow_int({left}, {right});"
                                )
                                lines.append(
                                    "    if (py_error_occurred()) goto cleanup;"
                                )

                        # Python modulo
                        elif op == "%":
                            if instruction.value_type == ValueType.FLOAT:
                                lines.append(
                                    f"    {instruction.target} = fmod({left}, {right});"
                                )
                            else:
                                lines.append(
                                    f"    {instruction.target} = py_mod_int({left}, {right});"
                                )
                                lines.append(
                                    "    if (py_error_occurred()) goto cleanup;"
                                )

                        # Python identity: `is` / `is not` → C pointer equality
                        elif op in {"is", "is not"}:
                            c_op = "==" if op == "is" else "!="
                            lines.append(
                                f"    {instruction.target} = "
                                f"({left} {c_op} {right});"
                            )

                        # normal operators
                        else:
                            lines.append(
                                f"    {instruction.target} = "
                                f"{left} {op} {right};"
                            )

                elif isinstance(instruction, UnaryOp):
                    lines.append(
                        f"    {instruction.target} = "
                        f"{instruction.op}{instruction.operand};"
                    )

                elif isinstance(instruction, Call):
                    call_text = self._emit_call(instruction, type_map)

                    if instruction.target is None:
                        if self.runtime.is_refcounted(instruction.value_type):
                            temp_name = self._next_temp()
                            c_type = c_type_name(instruction.value_type)
                            lines.append(
                                f"    {c_type} {temp_name} = {call_text};"
                            )
                            lines.append(
                                f"    py_decref({temp_name});"
                            )
                        else:
                            lines.append(f"    {call_text};")
                    else:
                        if self.runtime.is_refcounted(type_map.get(instruction.target, ValueType.UNKNOWN)):
                            lines.append(
                                f"    py_decref({instruction.target});"
                            )
                        lines.append(
                            f"    {instruction.target} = {call_text};"
                        )

                    if instruction.can_raise and instruction.exception_target:
                        if instruction.exception_live:
                            lines.append(
                                f"    /* exception live set: {', '.join(instruction.exception_live)} */"
                            )
                        lines.append(
                            f"    if (py_error_occurred()) goto {instruction.exception_target};"
                        )

                elif isinstance(instruction, Print):
                    lines.append(
                        f"    "
                        f"{self.runtime.print_call(instruction.value, instruction.value_type, instruction.newline)}"
                    )

                elif isinstance(instruction, DecRef):
                    lines.append(
                        f"    if ({instruction.target}) {{ py_decref({instruction.target}); {instruction.target} = NULL; }}"
                    )

            terminator = block.terminator

            if isinstance(terminator, JumpTerminator):
                lines.append(f"    goto {terminator.target};")

            elif isinstance(terminator, BranchTerminator):
                cond = terminator.condition
                cond_type = type_map.get(cond, ValueType.UNKNOWN)
                if cond_type in {
                    ValueType.INT,
                    ValueType.BOOL,
                    ValueType.FLOAT,
                    ValueType.STRING,
                    ValueType.LIST,
                    ValueType.TUPLE,
                }:
                    cond_expr = self.runtime.truthy_call(cond, cond_type)
                else:
                    # Fallback: C truthiness. Native backend doesn't fully support dynamic types yet.
                    cond_expr = cond

                lines.append(
                    f"    if ({cond_expr}) "
                    f"goto {terminator.true_target};"
                )
                lines.append(
                    f"    goto {terminator.false_target};"
                )

            elif isinstance(terminator, ReturnTerminator):
                if terminator.value is None:
                    lines.append("    goto cleanup;")
                else:
                    ret_type = type_map.get(terminator.value, ValueType.UNKNOWN)
                    if self.runtime.is_refcounted(ret_type):
                        lines.append(
                            f"    py_incref({terminator.value});"
                        )
                    lines.append(
                        f"    {ret_var} = {terminator.value};"
                    )
                    lines.append("    goto cleanup;")

        return lines

    def _next_temp(self) -> str:
        name = f"__tmp{self._temp_id}"
        self._temp_id += 1
        return name

    def _emit_cleanup(self, function: IRFunction, ret_var: str) -> list[str]:
        lines: list[str] = []
        lines.append("cleanup: ;")
        lines.extend(self._emit_decref_locals(function))
        if function.return_type == ValueType.VOID:
            lines.append("    return;")
        else:
            default_value = self._default_initializer(function.return_type)
            lines.append("    if (py_error_occurred()) {")
            lines.append(f"        return {default_value};")
            lines.append("    }")
            lines.append(f"    return {ret_var};")
        return lines

    def _emit_call(
        self,
        instruction: Call,
        type_map: dict[str, ValueType],
    ) -> str:
        """Generate a C function call."""

        if (
            instruction.func_name in ("str", "repr", "ascii")
            and len(instruction.args) == 1
        ):
            arg_type = type_map.get(
                instruction.args[0],
                ValueType.UNKNOWN,
            )

            converter = self.runtime.str_converter(arg_type)

            return f"{converter}({instruction.args[0]})"

        return f"{instruction.func_name}({', '.join(instruction.args)})"

    def _emit_decref_locals(self, function: IRFunction) -> list[str]:
        lines: list[str] = []
        params = set(name for name, _ in function.params)
        for name, value_type in sorted(function.locals.items(), reverse=True):
            if name in params:
                continue
            if self.runtime.is_refcounted(value_type):
                info = function.ownership.get(name) if hasattr(function, "ownership") else None
                if info is not None and not info.cleanup_required:
                    continue
                lines.append(f"    if ({name}) py_decref({name});")
        return lines

    @staticmethod
    def _build_type_map(
        function: IRFunction,
    ) -> dict[str, ValueType]:

        type_map: dict[str, ValueType] = {}

        for name, vtype in function.params:
            type_map[name] = vtype

        type_map.update(function.locals)

        return type_map

    @staticmethod
    def _default_initializer(value_type: ValueType) -> str:

        if value_type == ValueType.FLOAT:
            return "0.0"

        if value_type in (ValueType.INT, ValueType.BOOL):
            return "0"

        if value_type == ValueType.STRING:
            return "NULL"

        return "0"

    @staticmethod
    def _literal(
        value: object,
        value_type: ValueType,
    ) -> str:

        if value_type == ValueType.STRING:
            escaped = (
                str(value)
                .replace("\\", "\\\\")
                .replace('"', '\\"')
                .replace("\n", "\\n")
            )

            return f'"{escaped}"'

        if value_type == ValueType.BOOL:
            return "1" if value else "0"

        if value_type == ValueType.FLOAT:
            return repr(float(value))

        return str(int(value))
