from __future__ import annotations

from compiler.core.types import ValueType, c_type_name
from compiler.ir import (
    Assign,
    BasicBlock,
    BinaryOp,
    BranchTerminator,
    Call,
    IRFunction,
    IRModule,
    JumpTerminator,
    LoadConst,
    Print,
    ReturnTerminator,
    UnaryOp,
)
from compiler.runtime import CRuntimeSupport


class CCodeGenerator:
    def __init__(self) -> None:
        self.runtime = CRuntimeSupport()

    def generate(self, module: IRModule) -> str:
        lines = [
            "/* Generated by the Python-subset compiler */",
            "#include <math.h>",
            self.runtime.include_directive(),
            "",
        ]

        for name, value_type in sorted(module.globals.items()):
            lines.append(
                f"{c_type_name(value_type)} {name} = {self._default_initializer(value_type)};"
            )

        if module.globals:
            lines.append("")

        for function in module.functions:
            lines.append(self._prototype(function) + ";")

        if module.functions:
            lines.append("")

        for function in module.functions:
            lines.extend(self._emit_function(function))
            lines.append("")

        lines.extend(self._emit_main(module.main))

        return "\n".join(lines).rstrip() + "\n"

    def _emit_main(self, function: IRFunction) -> list[str]:
        lines = ["int main(void) {"]
        lines.extend(self._emit_locals(function))
        lines.extend(self._emit_blocks(function.blocks, function))
        lines.append("}")
        return lines

    def _emit_function(self, function: IRFunction) -> list[str]:
        lines = [f"{self._prototype(function)} {{"]

        lines.extend(self._emit_locals(function))
        lines.extend(self._emit_blocks(function.blocks, function))

        lines.append("}")
        return lines

    def _prototype(self, function: IRFunction) -> str:
        params = ", ".join(
            f"{c_type_name(value_type)} {name}"
            for name, value_type in function.params
        )

        return f"{c_type_name(function.return_type)} {function.name}({params or 'void'})"

    def _emit_locals(self, function: IRFunction) -> list[str]:
        locals_only = {
            name: value_type
            for name, value_type in function.locals.items()
            if name not in dict(function.params)
        }

        if not locals_only:
            return []

        lines = []

        for name, value_type in sorted(locals_only.items()):
            lines.append(
                f"    {c_type_name(value_type)} {name} = {self._default_initializer(value_type)};"
            )

        lines.append("")
        return lines

    def _emit_blocks(
        self,
        blocks: list[BasicBlock],
        function: IRFunction,
    ) -> list[str]:

        type_map = self._build_type_map(function)

        lines: list[str] = []

        for block in blocks:
            lines.append(f"{block.name}: ;")

            for instruction in block.instructions:

                if isinstance(instruction, LoadConst):
                    lines.append(
                        f"    {instruction.target} = "
                        f"{self._literal(instruction.value, instruction.value_type)};"
                    )

                elif isinstance(instruction, Assign):
                    lines.append(
                        f"    {instruction.target} = {instruction.source};"
                    )

                elif isinstance(instruction, BinaryOp):

                    # string concatenation
                    if (
                        instruction.value_type == ValueType.STRING
                        and instruction.op == "+"
                    ):
                        lines.append(
                            f"    {instruction.target} = "
                            f"py_str_concat({instruction.left}, {instruction.right});"
                        )

                    else:
                        left = instruction.left
                        right = instruction.right
                        op = instruction.op

                        # float promotion
                        if (
                            instruction.value_type == ValueType.FLOAT
                            and op in {"+", "-", "*", "/", "%"}
                        ):
                            left = f"((double) {left})"
                            right = f"((double) {right})"

                        # Python floor division
                        if op == "//":
                            if instruction.value_type == ValueType.FLOAT:
                                lines.append(
                                    f"    {instruction.target} = floor({left} / {right});"
                                )
                            else:
                                lines.append(
                                    f"    {instruction.target} = py_floor_div_int({left}, {right});"
                                )

                        # Python exponentiation
                        elif op == "**":
                            if instruction.value_type == ValueType.FLOAT:
                                lines.append(
                                    f"    {instruction.target} = pow({left}, {right});"
                                )
                            else:
                                lines.append(
                                    f"    {instruction.target} = py_pow_int({left}, {right});"
                                )

                        # Python modulo
                        elif op == "%":
                            if instruction.value_type == ValueType.FLOAT:
                                lines.append(
                                    f"    {instruction.target} = fmod({left}, {right});"
                                )
                            else:
                                lines.append(
                                    f"    {instruction.target} = py_mod_int({left}, {right});"
                                )

                        # normal operators
                        else:
                            lines.append(
                                f"    {instruction.target} = "
                                f"{left} {op} {right};"
                            )

                elif isinstance(instruction, UnaryOp):
                    lines.append(
                        f"    {instruction.target} = "
                        f"{instruction.op}{instruction.operand};"
                    )

                elif isinstance(instruction, Call):
                    call_text = self._emit_call(instruction, type_map)

                    if instruction.target is None:
                        lines.append(f"    {call_text};")
                    else:
                        lines.append(
                            f"    {instruction.target} = {call_text};"
                        )

                elif isinstance(instruction, Print):
                    lines.append(
                        f"    "
                        f"{self.runtime.print_call(instruction.value, instruction.value_type, instruction.newline)}"
                    )

            terminator = block.terminator

            if isinstance(terminator, JumpTerminator):
                lines.append(f"    goto {terminator.target};")

            elif isinstance(terminator, BranchTerminator):
                cond = terminator.condition
                cond_type = type_map.get(cond, ValueType.UNKNOWN)
                if cond_type == ValueType.INT or cond_type == ValueType.BOOL:
                    cond_expr = f"py_truthy_int({cond})"
                elif cond_type == ValueType.FLOAT:
                    cond_expr = f"py_truthy_float({cond})"
                elif cond_type == ValueType.STRING:
                    cond_expr = f"py_truthy_str({cond})"
                else:
                    # Fallback: C truthiness. Native backend doesn't fully support dynamic types yet.
                    cond_expr = cond

                lines.append(
                    f"    if ({cond_expr}) "
                    f"goto {terminator.true_target};"
                )
                lines.append(
                    f"    goto {terminator.false_target};"
                )

            elif isinstance(terminator, ReturnTerminator):

                if terminator.value is None:
                    lines.append("    return;")

                else:
                    lines.append(
                        f"    return {terminator.value};"
                    )

        return lines

    def _emit_call(
        self,
        instruction: Call,
        type_map: dict[str, ValueType],
    ) -> str:
        """Generate a C function call."""

        if (
            instruction.func_name in ("str", "repr", "ascii")
            and len(instruction.args) == 1
        ):
            arg_type = type_map.get(
                instruction.args[0],
                ValueType.UNKNOWN,
            )

            converter = self.runtime.str_converter(arg_type)

            return f"{converter}({instruction.args[0]})"

        return f"{instruction.func_name}({', '.join(instruction.args)})"

    @staticmethod
    def _build_type_map(
        function: IRFunction,
    ) -> dict[str, ValueType]:

        type_map: dict[str, ValueType] = {}

        for name, vtype in function.params:
            type_map[name] = vtype

        type_map.update(function.locals)

        return type_map

    @staticmethod
    def _default_initializer(value_type: ValueType) -> str:

        if value_type == ValueType.FLOAT:
            return "0.0"

        if value_type in (ValueType.INT, ValueType.BOOL):
            return "0"

        if value_type == ValueType.STRING:
            return '""'

        return "0"

    @staticmethod
    def _literal(
        value: object,
        value_type: ValueType,
    ) -> str:

        if value_type == ValueType.STRING:
            escaped = (
                str(value)
                .replace("\\", "\\\\")
                .replace('"', '\\"')
                .replace("\n", "\\n")
            )

            return f'"{escaped}"'

        if value_type == ValueType.BOOL:
            return "1" if value else "0"

        if value_type == ValueType.FLOAT:
            return repr(float(value))

        return str(int(value))